version: '3.7'

services:
  client:
    image: uptime_client:latest
    restart: always
    environment:
      UPTIME_APP_API_BASE_URL: "https://prism.uprock.com/api/v1"
    ports:
      - "8080:80"
    depends_on:
      - server

  server:
    image: uptime_server:latest
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - server.env
    depends_on:
      - redis
      - mongodb

  redis:
    image: uptime_redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s

  mongodb:
    image: uptime_database_mongo:latest
    restart: always
    command: ["mongod", "--quiet", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/init/create_users.js:/docker-entrypoint-initdb.d/create_users.js
    env_file:
      - mongo.env
