{{- if .Values.worker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkmate-worker
spec:
  {{- if not .Values.worker.autoscaling.enabled }}
  replicas: {{ .Values.worker.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: checkmate-worker
  template:
    metadata:
      labels:
        app: checkmate-worker
    spec:
      terminationGracePeriodSeconds: {{ .Values.worker.terminationGracePeriodSeconds }}
    {{- with .Values.worker.affinity }}
      affinity:
        {{- tpl ( . | toYaml) $ | nindent 8 }}
    {{- end }}
    {{- with .Values.worker.tolerations }}
      tolerations:
        {{- tpl ( . | toYaml) $ | nindent 8 }}
    {{- end }}
      containers:
        - name: worker
          image: {{ include "checkmate.image" (dict "image" (.Values.worker.image | default .Values.server.controllers.main.containers.main.image.repository) "tag" (.Values.worker.tag | default .Values.server.controllers.main.containers.main.image.tag) "root" $) }}
          imagePullPolicy: {{ .Values.worker.imagePullPolicy }}
          ports:
            - name: health
              containerPort: {{ .Values.worker.healthPort }}
          envFrom:
            - secretRef:
                name: checkmate-secrets
          env:
          - name: CLIENT_HOST
            value: {{ .Values.server.controllers.main.containers.main.env.CLIENT_HOST | quote }}
          - name: QUEUE_MODE
            value: "worker"
          - name: HEALTH_PORT
            value: {{ .Values.worker.healthPort | quote }}
          livenessProbe:
            httpGet:
              path: /livez
              port: health
            initialDelaySeconds: {{ .Values.worker.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.worker.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.worker.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.worker.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            initialDelaySeconds: {{ .Values.worker.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.worker.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.worker.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.worker.probes.readiness.failureThreshold }}
          {{- with .Values.worker.resources }}
          resources:
              {{- tpl ( . | toYaml) $ | nindent 12 }}
          {{- end }}
{{- end }}
