{{- if .Values.mongodb.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "checkmate.fullname" . }}-mongodb
  namespace: {{ include "checkmate.namespace" . }}
  labels:
    {{- include "checkmate.componentLabels" (dict "root" . "component" "mongodb") | nindent 4 }}
  {{- with .Values.global.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  serviceName: {{ include "checkmate.fullname" . }}-mongodb
  selector:
    matchLabels:
      {{- include "checkmate.componentSelectorLabels" (dict "root" . "component" "mongodb") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "checkmate.componentSelectorLabels" (dict "root" . "component" "mongodb") | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mongodb.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mongodb.affinity }}
      affinity:
        {{- include "checkmate.tplrender" (dict "value" . "context" $) | nindent 8 }}
      {{- end }}
      {{- with .Values.mongodb.tolerations }}
      tolerations:
        {{- include "checkmate.tplrender" (dict "value" . "context" $) | nindent 8 }}
      {{- end }}
      containers:
        - name: mongodb
          image: {{ .Values.mongodb.image }}
          imagePullPolicy: {{ .Values.mongodb.imagePullPolicy }}
          ports:
            - name: mongodb
              containerPort: {{ .Values.mongodb.port }}
              protocol: TCP
          command: ["mongod", "--quiet", "--bind_ip_all"]
          volumeMounts:
            - name: data
              mountPath: /data/db
          {{- with .Values.mongodb.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        {{- $sc := include "checkmate.mongodbStorageClass" . }}
        {{- if $sc }}
        storageClassName: {{ $sc | quote }}
        {{- end }}
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ include "checkmate.mongodbPVCSize" . | quote }}
{{- end }}