{{- if .Values.client.enabled }}
  {{- $clientHost := (index .Values.client.ingress.main.hosts 0).host }}

  {{- if eq $clientHost "change_me" }}
    {{- fail "client.ingress.main.hosts[0].host must be overridden and not set to 'change_me'" }}
  {{- end }}

  {{- if or (not .Values.client.controllers.main.containers.main.env.UPTIME_APP_API_BASE_URL) (contains "change_me" .Values.client.controllers.main.containers.main.env.UPTIME_APP_API_BASE_URL) }}
    {{- fail "client.controllers.main.containers.main.env.UPTIME_APP_API_BASE_URL must be set to the public server URL" }}
  {{- end }}
{{- end }}

{{- if .Values.server.enabled }}
  {{- $serverHost := (index .Values.server.ingress.main.hosts 0).host }}

  {{- if eq $serverHost "change_me" }}
    {{- fail "server.ingress.main.hosts[0].host must be overridden and not set to 'change_me'" }}
  {{- end }}

  {{- if or (not .Values.server.controllers.main.containers.main.env.CLIENT_HOST) (contains "change_me" .Values.server.controllers.main.containers.main.env.CLIENT_HOST) }}
    {{- fail "server.controllers.main.containers.main.env.CLIENT_HOST must be set to the public client URL" }}
  {{- end }}
{{- end }}
