{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "checkmate.fullname" . }}-redis
  namespace: {{ include "checkmate.namespace" . }}
  labels:
    {{- include "checkmate.componentLabels" (dict "root" . "component" "redis") | nindent 4 }}
  {{- with .Values.global.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  serviceName: {{ include "checkmate.fullname" . }}-redis
  selector:
    matchLabels:
      {{- include "checkmate.componentSelectorLabels" (dict "root" . "component" "redis") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "checkmate.componentSelectorLabels" (dict "root" . "component" "redis") | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.affinity }}
      affinity:
        {{- include "checkmate.tplrender" (dict "value" . "context" $) | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.tolerations }}
      tolerations:
        {{- include "checkmate.tplrender" (dict "value" . "context" $) | nindent 8 }}
      {{- end }}
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          imagePullPolicy: {{ .Values.redis.imagePullPolicy }}
          ports:
            - name: redis
              containerPort: {{ .Values.redis.port }}
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
          {{- with .Values.redis.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        {{- $sc := include "checkmate.redisStorageClass" . }}
        {{- if $sc }}
        storageClassName: {{ $sc | quote }}
        {{- end }}
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ include "checkmate.redisPVCSize" . | quote }}
{{- end }}