apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkmate-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkmate-server
  template:
    metadata:
      labels:
        app: checkmate-server
    spec:
    {{- with .Values.server.affinity }}
      affinity:
        {{- tpl ( . | toYaml) $ | nindent 8 }}
    {{- end }}
    {{- with .Values.server.tolerations }}
      tolerations:
        {{- tpl ( . | toYaml) $ | nindent 8 }}
    {{- end }}
      containers:
        - name: server
          image: {{ .Values.server.image }}
          ports:
            - containerPort: {{ .Values.server.port }}
          envFrom:
            - secretRef:
                name: checkmate-secrets
          {{- with .Values.server.resources }}
          resources:
              {{- tpl ( . | toYaml) $ | nindent 12 }}
          {{- end }}
          env:
          - name: CLIENT_HOST
            value: "http://{{ .Values.client.ingress.host }}"
