apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkmate-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkmate-server
  template:
    metadata:
      labels:
        app: checkmate-server
    spec:
      containers:
        - name: server
          image: {{ .Values.server.image }}
          ports:
            - containerPort: {{ .Values.server.port }}
          envFrom:
            - secretRef:
                name: checkmate-secrets
          env:
          - name: CLIENT_HOST
            value: "http://{{ .Values.client.ingress.host }}"
