apiVersion: v1
kind: Service
metadata:
  name: {{ include "checkmate.fullname" . }}-server
  namespace: {{ include "checkmate.namespace" . }}
  labels:
    {{- include "checkmate.componentLabels" (dict "root" . "component" "server") | nindent 4 }}
  {{- with .Values.global.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "checkmate.componentSelectorLabels" (dict "root" . "component" "server") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.server.port }}
      targetPort: http
      protocol: TCP
