import { Router, RequestHandler } from "express";
import { isAllowed } from "@/api/middleware/isAllowed.js";
import { imageUpload } from "@/api/middleware/upload.js";
import { IAuthController } from "@/api/controllers/authController.js";
import { RouteTable } from "@/api/routes/defineRoutes.js";
import {
	authPayloadResponseSchema,
	superadminExistsResponseSchema,
	loginValidation,
	newPasswordValidation,
	recoveryTokenBodyValidation,
	recoveryValidation,
	registrationBodyValidation,
} from "@/api/validation/authValidation.js";
import {
	createUserBodyValidation,
	editUserBodyValidation,
	editUserByIdBodyValidation,
	editUserByIdParamValidation,
	editUserPasswordByIdBodyValidation,
	getUserByIdParamValidation,
	userResponseExample,
	userResponseSchema,
	userListResponseSchema,
} from "@/api/validation/userValidation.js";
import { errorJson, json, okJson, standardErrors } from "@/api/routes/openapiHelpers.js";

export const authRoutes: RouteTable<IAuthController> = {
	prefix: "/auth",
	tag: "auth",
	auth: "jwt",
	routes: [
		{
			method: "post",
			path: "/register",
			handler: "registerUser",
			summary: "Register a new user (first user becomes superadmin)",
			auth: "none",
			upload: "profileImage",
			body: registrationBodyValidation,
			response: authPayloadResponseSchema,
		},
		{
			method: "post",
			path: "/login",
			handler: "loginUser",
			summary: "Log in",
			auth: "none",
			body: loginValidation,
			response: authPayloadResponseSchema,
			spec: (d) => ({
				...d,
				request: { body: { content: json(loginValidation, { email: "ada@example.com", password: "S3cure!Passw0rd" }) } },
				responses: {
					"200": okJson(authPayloadResponseSchema, "OK", { user: userResponseExample, token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..." }),
					"401": errorJson("Invalid credentials"),
					"500": standardErrors["500"],
				},
			}),
		},
		{
			method: "post",
			path: "/recovery/request",
			handler: "requestRecovery",
			summary: "Request a password recovery email",
			auth: "none",
			body: recoveryValidation,
			spec: (d) => ({ ...d, request: { body: { content: json(recoveryValidation, { email: "ada@example.com" }) } } }),
		},
		{
			method: "post",
			path: "/recovery/validate",
			handler: "validateRecovery",
			summary: "validate a password recovery token",
			auth: "none",
			body: recoveryTokenBodyValidation,
		},
		{
			method: "post",
			path: "/recovery/reset",
			handler: "resetPassword",
			summary: "Reset password using a recovery token",
			auth: "none",
			body: newPasswordValidation,
		},
		{
			method: "get",
			path: "/users/superadmin",
			handler: "checkSuperadminExists",
			summary: "Check whether a superadmin user exists",
			auth: "none",
			response: superadminExistsResponseSchema,
		},

		{
			method: "get",
			path: "/users",
			handler: "getAllUsers",
			summary: "List all users (admin/superadmin)",
			roles: ["admin", "superadmin"],
			response: userListResponseSchema,
		},
		{
			method: "post",
			path: "/users",
			handler: "createUser",
			summary: "Create a new user (superadmin)",
			roles: ["superadmin"],
			upload: "profileImage",
			body: createUserBodyValidation,
			response: userResponseSchema,
			spec: (d) => ({ ...d, responses: { "201": okJson(userResponseSchema, "User created"), ...standardErrors } }),
		},
		{
			method: "get",
			path: "/users/:userId",
			handler: "getUserById",
			summary: "Get a user by id",
			roles: ["admin", "superadmin"],
			params: getUserByIdParamValidation,
			response: userResponseSchema,
			spec: (d) => ({ ...d, responses: { ...d.responses, "404": errorJson("User not found") } }),
		},
		{
			method: "patch",
			path: "/users/:userId",
			handler: "editUserById",
			summary: "Edit a user (superadmin)",
			roles: ["superadmin"],
			params: editUserByIdParamValidation,
			body: editUserByIdBodyValidation,
		},
		{
			method: "patch",
			path: "/users/:userId/password",
			handler: "editUserPasswordById",
			summary: "Change a user's password (superadmin)",
			roles: ["superadmin"],
			params: editUserByIdParamValidation,
			body: editUserPasswordByIdBodyValidation,
		},
		{
			method: "delete",
			path: "/users/:userId",
			handler: "deleteUserById",
			summary: "Delete a user (admin/superadmin)",
			roles: ["admin", "superadmin"],
			params: getUserByIdParamValidation,
		},
		{
			method: "patch",
			path: "/user",
			handler: "editUser",
			summary: "Edit the currently authenticated user",
			roles: ["admin", "superadmin", "user"],
			upload: "profileImage",
			body: editUserBodyValidation,
			response: userResponseSchema,
		},
		{
			method: "delete",
			path: "/user",
			handler: "deleteUser",
			summary: "Delete the currently authenticated user",
			roles: ["admin", "superadmin", "user"],
		},
	],
};
