import { IMonitorController } from "@/api/controllers/monitorController.js";
import { RouteTable } from "@/api/routes/defineRoutes.js";
import { okJson } from "@/api/routes/openapiHelpers.js";
import {
	getMonitorByIdParamValidation,
	getMonitorByIdQueryValidation,
	getMonitorsByTeamIdQueryValidation,
	getMonitorsWithChecksQueryValidation,
	getCertificateParamValidation,
	getDomainParamValidation,
	createMonitorBodyValidation,
	editMonitorBodyValidation,
	pauseMonitorParamValidation,
	bulkPauseMonitorBodyValidation,
	getUptimeDetailsByIdParamValidation,
	getUptimeDetailsByIdQueryValidation,
	importMonitorsBodyValidation,
	getHardwareDetailsByIdParamValidation,
	getHardwareDetailsByIdQueryValidation,
	getDockerDetailsByIdParamValidation,
	getDockerDetailsByIdQueryValidation,
	getDockerContainerNameParamValidation,
	getDockerContainerByNameQueryValidation,
	getDockerContainerLogsQueryValidation,
	bulkPauseResponseSchema,
	certificateResponseSchema,
	demoMonitorsResponseSchema,
	domainResponseSchema,
	importMonitorsResponseSchema,
	monitorListResponseSchema,
	updateNotificationsResponseSchema,
} from "@/api/validation/monitorValidation.js";
import { updateNotificationsValidation } from "@/api/validation/notificationValidation.js";
import { dockerLogPageSchema } from "@/domain/docker/docker-log.schema.js";
import { groupedGeoCheckResultSchema } from "@/domain/geo-checks/geo-check.schema.js";
import {
	dockerContainerDetailsResultSchema,
	dockerDetailsResultSchema,
	gamesMapSchema,
	hardwareDetailsResultSchema,
	monitorResponseSchema,
	monitorsWithChecksByTeamIdResultSchema,
	pageSpeedDetailsResultSchema,
	uptimeDetailsResultSchema,
} from "@/domain/monitors/monitor.schema.js";

export const monitorRoutes: RouteTable<IMonitorController> = {
	prefix: "/monitors",
	tag: "monitors",
	auth: "jwt",
	routes: [
		{
			method: "get",
			path: "/team",
			handler: "getMonitorsByTeamId",
			summary: "List monitors for the caller's team",
			query: getMonitorsByTeamIdQueryValidation,
			response: monitorListResponseSchema,
		},
		{
			method: "get",
			path: "/team/with-checks",
			handler: "getMonitorsWithChecksByTeamId",
			summary: "List team monitors with their most recent checks (paginated)",
			query: getMonitorsWithChecksQueryValidation,
			response: monitorsWithChecksByTeamIdResultSchema,
		},
		{
			method: "get",
			path: "/uptime/details/:monitorId",
			handler: "getUptimeDetailsById",
			summary: "Get uptime details for a monitor",
			errors: { 400: "Invalid request, or the monitor is not an uptime monitor", 404: "Monitor or monitor stats not found" },
			params: getUptimeDetailsByIdParamValidation,
			query: getUptimeDetailsByIdQueryValidation,
			response: uptimeDetailsResultSchema,
		},
		{
			method: "get",
			path: "/hardware/details/:monitorId",
			handler: "getHardwareDetailsById",
			summary: "Get hardware metrics detail for a monitor",
			errors: { 400: "Invalid request, or the monitor is not a hardware monitor", 404: "Monitor or monitor stats not found" },
			params: getHardwareDetailsByIdParamValidation,
			query: getHardwareDetailsByIdQueryValidation,
			response: hardwareDetailsResultSchema,
		},
		{
			method: "get",
			path: "/pagespeed/details/:monitorId",
			handler: "getPageSpeedDetailsById",
			summary: "Get PageSpeed detail for a monitor",
			errors: { 400: "Invalid request, or the monitor is not a pagespeed monitor", 404: "Monitor or monitor stats not found" },
			params: getHardwareDetailsByIdParamValidation,
			query: getHardwareDetailsByIdQueryValidation,
			response: pageSpeedDetailsResultSchema,
		},
		{
			method: "get",
			path: "/docker/details/:monitorId",
			handler: "getDockerDetailsById",
			summary: "Get Docker host details for a monitor",
			errors: { 400: "Invalid request, or the monitor is not a Docker monitor", 404: "Monitor or monitor stats not found" },
			params: getDockerDetailsByIdParamValidation,
			query: getDockerDetailsByIdQueryValidation,
			response: dockerDetailsResultSchema,
		},
		{
			method: "get",
			path: "/docker/details/:monitorId/containers/:containerName",
			handler: "getDockerContainerByName",
			summary: "Get details for one container on a Docker host monitor",
			errors: { 400: "Invalid request, or the monitor is not a Docker monitor", 404: "Monitor not found" },
			params: getDockerContainerNameParamValidation,
			query: getDockerContainerByNameQueryValidation,
			response: dockerContainerDetailsResultSchema,
		},
		{
			method: "get",
			path: "/docker/details/:monitorId/containers/:containerName/logs",
			handler: "getDockerContainerLogs",
			summary: "Get stored log lines for one container on a Docker host monitor, newest first (admin/superadmin)",
			errors: { 400: "Invalid request, or the monitor is not a Docker monitor", 404: "Monitor not found" },
			roles: ["admin", "superadmin"],
			params: getDockerContainerNameParamValidation,
			query: getDockerContainerLogsQueryValidation,
			response: dockerLogPageSchema,
		},
		{
			method: "get",
			path: "/:monitorId/geo-checks",
			handler: "getGeoChecksByMonitorId",
			summary: "Get geo check results for a monitor",
			errors: { 404: "Monitor not found" },
			params: getMonitorByIdParamValidation,
			query: getMonitorByIdQueryValidation,
			response: groupedGeoCheckResultSchema,
		},
		{
			method: "post",
			path: "/pause/:monitorId",
			handler: "pauseMonitor",
			summary: "Toggle pause state for a monitor (admin/superadmin)",
			errors: { 404: "Monitor not found" },
			roles: ["admin", "superadmin"],
			params: pauseMonitorParamValidation,
			response: monitorResponseSchema,
		},
		{
			method: "post",
			path: "/bulk/pause",
			handler: "bulkPauseMonitors",
			summary: "Pause or resume several monitors (admin/superadmin)",
			roles: ["admin", "superadmin"],
			body: bulkPauseMonitorBodyValidation,
			response: bulkPauseResponseSchema,
		},
		{
			method: "get",
			path: "/certificate/:monitorId",
			handler: "getMonitorCertificate",
			summary: "Get SSL certificate info for a monitor",
			errors: { 404: "Monitor not found" },
			params: getCertificateParamValidation,
			response: certificateResponseSchema,
		},
		{
			method: "get",
			path: "/domain/:monitorId",
			handler: "getMonitorDomain",
			summary: "Get domain registration expiry for a monitor",
			errors: { 404: "Monitor not found" },
			params: getDomainParamValidation,
			response: domainResponseSchema,
		},
		{
			method: "patch",
			path: "/notifications",
			handler: "updateNotifications",
			summary: "Bulk update notifications across monitors (admin/superadmin)",
			errors: {
				400: "Invalid request, or one or more monitor or notification ids are invalid",
				403: "Caller lacks the role, or a notification belongs to another team",
			},
			roles: ["admin", "superadmin"],
			body: updateNotificationsValidation,
			response: updateNotificationsResponseSchema,
		},
		{
			method: "post",
			path: "/",
			handler: "createMonitor",
			summary: "Create a new monitor (admin/superadmin)",
			roles: ["admin", "superadmin"],
			body: createMonitorBodyValidation,
			response: monitorResponseSchema,
			spec: (d) => ({ ...d, responses: { ...d.responses, "200": okJson(monitorResponseSchema, "Monitor created") } }),
		},
		{
			method: "delete",
			path: "/",
			handler: "deleteAllMonitors",
			summary: "Delete every monitor (superadmin)",
			roles: ["superadmin"],
		},
		{
			method: "post",
			path: "/demo",
			handler: "addDemoMonitors",
			summary: "Insert preconfigured demo monitors (admin/superadmin)",
			roles: ["admin", "superadmin"],
			response: demoMonitorsResponseSchema,
		},
		{
			method: "get",
			path: "/export/json",
			handler: "exportMonitorsToJSON",
			summary: "Export all team monitors as JSON (admin/superadmin)",
			errors: { 400: "No monitors to export" },
			roles: ["admin", "superadmin"],
			response: monitorListResponseSchema,
		},
		{
			method: "post",
			path: "/import/json",
			handler: "importMonitorsFromJSON",
			summary: "Import monitors from JSON (admin/superadmin)",
			roles: ["admin", "superadmin"],
			body: importMonitorsBodyValidation,
			response: importMonitorsResponseSchema,
		},
		{
			method: "get",
			path: "/games",
			handler: "getAllGames",
			summary: "List supported game-server types",
			response: gamesMapSchema,
		},
		{
			method: "get",
			path: "/:monitorId",
			handler: "getMonitorById",
			summary: "Get a monitor by id",
			errors: { 404: "Monitor not found" },
			params: getMonitorByIdParamValidation,
			response: monitorResponseSchema,
		},
		{
			method: "patch",
			path: "/:monitorId",
			handler: "editMonitor",
			summary: "Edit a monitor (admin/superadmin)",
			errors: { 404: "Monitor not found", 422: "A TLS Docker host needs a key, or a hardware monitor needs a Capture API secret" },
			roles: ["admin", "superadmin"],
			params: getMonitorByIdParamValidation,
			body: editMonitorBodyValidation,
			response: monitorResponseSchema,
		},
		{
			method: "delete",
			path: "/:monitorId",
			handler: "deleteMonitor",
			summary: "Delete a monitor (admin/superadmin)",
			errors: { 404: "Monitor not found" },
			roles: ["admin", "superadmin"],
			params: getMonitorByIdParamValidation,
			response: monitorResponseSchema,
		},
	],
};
